# 한국은행

In [1]:
import requests 
import xml.etree.ElementTree as ET 
import pandas as pd

In [2]:
# 호출하려는 OpenAPI url
url = "http://ecos.bok.or.kr/api/StatisticSearch/sample/json/kr/1/10/060Y001/DD/202008/202108/010200000/"

# 정의된 url 호출
response = requests.get(url)

# json 형식으로 요청
data = response.json()

# [서비스명][row]
rdata = data['StatisticSearch']['row']

In [3]:
pd.DataFrame(rdata)

,UNIT_NAME,STAT_NAME,ITEM_CODE1,STAT_CODE,ITEM_CODE2,ITEM_CODE3,ITEM_NAME1,ITEM_NAME2,DATA_VALUE,ITEM_NAME3,TIME
0,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,0.799,,20200803
1,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,0.802,,20200804
2,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,0.795,,20200805
3,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,0.807,,20200806
4,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,0.81,,20200807
5,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,0.83,,20200810
6,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,0.818,,20200811
7,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,0.827,,20200812
8,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,0.815,,20200813
9,연%,4.1.1 시장금리(일별),010200000,060Y001,,,국고채(3년),,0.828,,20200814

'<?xml version="1.0" encoding="UTF-8"?><StatisticItemList>\n<list_total_count>581</list_total_count>\n<row>\n<STAT_CODE>021Y125</STAT_CODE>\n<STAT_NAME>7.4.1 소비자물가지수(2020=100)(전국)</STAT_NAME>\n<GRP_CODE>Group1</GRP_CODE>\n<GRP_NAME>소비자물가지수(2020=100)(전국)</GRP_NAME>\n<P_ITEM_CODE/>\n<ITEM_CODE>0</ITEM_CODE>\n<ITEM_NAME>총지수</ITEM_NAME>\n<CYCLE>MM</CYCLE>\n<START_TIME>196501</START_TIME>\n<END_TIME>202112</END_TIME>\n<DATA_CNT>684</DATA_CNT>\n<WEIGHT>1000</WEIGHT>\n</row>\n</StatisticItemList>'

# 통계청

In [2]:
import json
from urllib.request import urlopen

from PyQt5 import QtWidgets
from PyQt5.QtWidgets import *
import functools as fc
import sys

통계목록

In [3]:
#클릭한 목록에 대한 하위 목록 생성
class NewWindow(QtWidgets.QMainWindow):
    def __init__(self, parent=None):
        super(NewWindow, self).__init__(parent)
        centralWidget = QWidget()
        self.setCentralWidget(centralWidget)
        self.setGeometry(300, 300, 500, 500)

        Setting(self, List_Id)

#최상위 목록 생성
class MyWindow(QtWidgets.QMainWindow, QPushButton):
    def __init__(self):
        super(MyWindow, self).__init__()
        centralWidget = QWidget()
        self.setCentralWidget(centralWidget)
        self.setGeometry(200, 200, 500, 500)
        self.setStyleSheet("background-color: white")

        Setting(self, 'A')
        
#목록 셋팅 함수
def Setting(self, parentId):
    #url을 통해 json 데이터 가져오기
    with urlopen(
            "https://kosis.kr/openapi/statisticsList.do?method=getList&apiKey=ZjZjOTI3MjRjNmU1YzdhZTMwOWRjNjgxN2MzNDgwNmY=&vwCd=MT_ZTITLE&parentListId="+parentId+"&format=json&jsonVD=Y") as url:
        json_file = url.read()

    py_json = json.loads(json_file.decode('utf-8'))

    #하위 목록이 있다면 LinkButton, 하위 목록이 없다면 label로 생성
    for i, v in enumerate(py_json):
        if 'LIST_NM' in v:
            btn = QCommandLinkButton(v['LIST_NM'], self)
            btn.setStyleSheet("Text-align: left;"
                             "border: none;"
                             )
            btn.setGeometry(100, 50 * i, 500, 40)
            btn.clicked.connect(fc.partial(Action, self, v['LIST_ID']))
        else:
            lbl = QLabel(v['TBL_NM'], self)
            lbl.setGeometry(100, 50 * i, 500, 40)


def Action(self, check):
    global List_Id
    List_Id = check

    NewWindow(self).show()


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    window = MyWindow()
    window.show()
    sys.exit(app.exec_())

SystemExit: 0

C:\Users\User\anaconda3\envs\kw\lib\site-packages\IPython\core\interactiveshell.py:3452: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)